//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Despatch
{

    private string customerNameField;

    private string customerEmailField;

    private string carrierNameField;

    private string serviceTypeNameField;

    private string serviceTypeCodeField;

    private string salesOrderNumberField;

    private string orderStatusField;

    private string customerPurchaseOrderReferenceNumberField;

    private string requestedDeliveryDateField;

    private string shippingCostField;

    private string customerReferenceField;

    private string customerPhoneField;

    private string customerMobileField;

    private string totalSaleField;

    private string discountField;

    private string taxPaidField;

    private string createdDateField;

    private string channelNameField;

    private string onHoldField;

    private string invoiceAddressLine1Field;

    private string invoiceAddressLine2Field;

    private string invoiceAddressTownCityField;

    private string invoiceAddressRegionField;

    private string invoiceAddressPostCodeField;

    private string invoiceAddressCountryField;

    private string shippingAddressLine1Field;

    private string shippingAddressLine2Field;

    private string shippingAddressTownCityField;

    private string shippingAddressRegionField;

    private string shippingAddressPostCodeField;

    private string shippingAddressCountryField;

    private string despatchNumberField;

    private string numberOfPackagesField;

    private string despatchDateField;

    private DespatchItem[] itemsField;

    private DespatchDespatchPackage[] packagesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerName
    {
        get
        {
            return this.customerNameField;
        }
        set
        {
            this.customerNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerEmail
    {
        get
        {
            return this.customerEmailField;
        }
        set
        {
            this.customerEmailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CarrierName
    {
        get
        {
            return this.carrierNameField;
        }
        set
        {
            this.carrierNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceTypeName
    {
        get
        {
            return this.serviceTypeNameField;
        }
        set
        {
            this.serviceTypeNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ServiceTypeCode
    {
        get
        {
            return this.serviceTypeCodeField;
        }
        set
        {
            this.serviceTypeCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SalesOrderNumber
    {
        get
        {
            return this.salesOrderNumberField;
        }
        set
        {
            this.salesOrderNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OrderStatus
    {
        get
        {
            return this.orderStatusField;
        }
        set
        {
            this.orderStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPurchaseOrderReferenceNumber
    {
        get
        {
            return this.customerPurchaseOrderReferenceNumberField;
        }
        set
        {
            this.customerPurchaseOrderReferenceNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequestedDeliveryDate
    {
        get
        {
            return this.requestedDeliveryDateField;
        }
        set
        {
            this.requestedDeliveryDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShippingCost
    {
        get
        {
            return this.shippingCostField;
        }
        set
        {
            this.shippingCostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerReference
    {
        get
        {
            return this.customerReferenceField;
        }
        set
        {
            this.customerReferenceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerPhone
    {
        get
        {
            return this.customerPhoneField;
        }
        set
        {
            this.customerPhoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerMobile
    {
        get
        {
            return this.customerMobileField;
        }
        set
        {
            this.customerMobileField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TotalSale
    {
        get
        {
            return this.totalSaleField;
        }
        set
        {
            this.totalSaleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Discount
    {
        get
        {
            return this.discountField;
        }
        set
        {
            this.discountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TaxPaid
    {
        get
        {
            return this.taxPaidField;
        }
        set
        {
            this.taxPaidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CreatedDate
    {
        get
        {
            return this.createdDateField;
        }
        set
        {
            this.createdDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ChannelName
    {
        get
        {
            return this.channelNameField;
        }
        set
        {
            this.channelNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OnHold
    {
        get
        {
            return this.onHoldField;
        }
        set
        {
            this.onHoldField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceAddressLine1
    {
        get
        {
            return this.invoiceAddressLine1Field;
        }
        set
        {
            this.invoiceAddressLine1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceAddressLine2
    {
        get
        {
            return this.invoiceAddressLine2Field;
        }
        set
        {
            this.invoiceAddressLine2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceAddressTownCity
    {
        get
        {
            return this.invoiceAddressTownCityField;
        }
        set
        {
            this.invoiceAddressTownCityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceAddressRegion
    {
        get
        {
            return this.invoiceAddressRegionField;
        }
        set
        {
            this.invoiceAddressRegionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceAddressPostCode
    {
        get
        {
            return this.invoiceAddressPostCodeField;
        }
        set
        {
            this.invoiceAddressPostCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceAddressCountry
    {
        get
        {
            return this.invoiceAddressCountryField;
        }
        set
        {
            this.invoiceAddressCountryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShippingAddressLine1
    {
        get
        {
            return this.shippingAddressLine1Field;
        }
        set
        {
            this.shippingAddressLine1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShippingAddressLine2
    {
        get
        {
            return this.shippingAddressLine2Field;
        }
        set
        {
            this.shippingAddressLine2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShippingAddressTownCity
    {
        get
        {
            return this.shippingAddressTownCityField;
        }
        set
        {
            this.shippingAddressTownCityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShippingAddressRegion
    {
        get
        {
            return this.shippingAddressRegionField;
        }
        set
        {
            this.shippingAddressRegionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ShippingAddressPostCode
    {
        get
        {
            return this.shippingAddressPostCodeField;
        }
        set
        {
            this.shippingAddressPostCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public virtual string ShippingAddressCountry
    {
        get
        {
            return this.shippingAddressCountryField;
        }
        set
        {
            this.shippingAddressCountryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DespatchNumber
    {
        get
        {
            return this.despatchNumberField;
        }
        set
        {
            this.despatchNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public virtual string NumberOfPackages
    {
        get
        {
            return this.numberOfPackagesField;
        }
        set
        {
            this.numberOfPackagesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DespatchDate
    {
        get
        {
            return this.despatchDateField;
        }
        set
        {
            this.despatchDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public DespatchItem[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DespatchPackage", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public DespatchDespatchPackage[] Packages
    {
        get
        {
            return this.packagesField;
        }
        set
        {
            this.packagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class DespatchItem
{

    private string nameField;

    private string descriptionField;

    private string itemCodeField;

    private string defaultSuppliersPartNumberField;

    private string barcodeField;

    private string defaultNumberItemsPerContainerField;

    private string defaultNumberItemsPerOuterCaseField;

    private string buyPriceField;

    private string wholesalePriceField;

    private string retailPriceField;

    private string weightField;

    private string heightField;

    private string widthField;

    private string depthField;

    private string tagsField;

    private string attribute1Field;

    private string attribute2Field;

    private string attribute3Field;

    private string itemGroupNameField;

    private string salePriceField;

    private string quantityOrderedField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ItemCode
    {
        get
        {
            return this.itemCodeField;
        }
        set
        {
            this.itemCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DefaultSuppliersPartNumber
    {
        get
        {
            return this.defaultSuppliersPartNumberField;
        }
        set
        {
            this.defaultSuppliersPartNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Barcode
    {
        get
        {
            return this.barcodeField;
        }
        set
        {
            this.barcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DefaultNumberItemsPerContainer
    {
        get
        {
            return this.defaultNumberItemsPerContainerField;
        }
        set
        {
            this.defaultNumberItemsPerContainerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DefaultNumberItemsPerOuterCase
    {
        get
        {
            return this.defaultNumberItemsPerOuterCaseField;
        }
        set
        {
            this.defaultNumberItemsPerOuterCaseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BuyPrice
    {
        get
        {
            return this.buyPriceField;
        }
        set
        {
            this.buyPriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WholesalePrice
    {
        get
        {
            return this.wholesalePriceField;
        }
        set
        {
            this.wholesalePriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RetailPrice
    {
        get
        {
            return this.retailPriceField;
        }
        set
        {
            this.retailPriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Weight
    {
        get
        {
            return this.weightField;
        }
        set
        {
            this.weightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Depth
    {
        get
        {
            return this.depthField;
        }
        set
        {
            this.depthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Tags
    {
        get
        {
            return this.tagsField;
        }
        set
        {
            this.tagsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Attribute1
    {
        get
        {
            return this.attribute1Field;
        }
        set
        {
            this.attribute1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Attribute2
    {
        get
        {
            return this.attribute2Field;
        }
        set
        {
            this.attribute2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Attribute3
    {
        get
        {
            return this.attribute3Field;
        }
        set
        {
            this.attribute3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ItemGroupName
    {
        get
        {
            return this.itemGroupNameField;
        }
        set
        {
            this.itemGroupNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SalePrice
    {
        get
        {
            return this.salePriceField;
        }
        set
        {
            this.salePriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string QuantityOrdered
    {
        get
        {
            return this.quantityOrderedField;
        }
        set
        {
            this.quantityOrderedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class DespatchDespatchPackage
{

    private string depthField;

    private string heightField;

    private string weightField;

    private string widthField;

    private string packageNameField;

    private string trackingNumberField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Depth
    {
        get
        {
            return this.depthField;
        }
        set
        {
            this.depthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Weight
    {
        get
        {
            return this.weightField;
        }
        set
        {
            this.weightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PackageName
    {
        get
        {
            return this.packageNameField;
        }
        set
        {
            this.packageNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TrackingNumber
    {
        get
        {
            return this.trackingNumberField;
        }
        set
        {
            this.trackingNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private Despatch[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Despatch")]
    public Despatch[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
